application: greatshipgroup
version: live
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /s
  static_dir: public
  secure: never

- url: /favicon.ico
  static_files: public/image/icon/favicon.png
  upload: public/image/icon/favicon.png
  secure: never

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: never

- url: /uds/css
  static_dir: public/image/uds
  secure: never

- url: /appengine_admin_media/
  static_dir: lib/appengine_admin/media
  secure: never

- url: /console/static/
  static_dir: lib/console/app/view/static
  secure: never

- url: /console.*
  script: lib/console/app/console.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /dl.*
  script: static.py

- url: /admin.*
  script: admin.py
  login: admin

- url: /.*
  script: handlers.py

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.bak)|
  (.*\.gitignore)|
  (\..*)
  )$
